(()=>{'use strict';const {KEY,BASE,esc}=ReliableStore;let data=ReliableStore.data,screen='quotes',quotes=[];const main=document.querySelector('#admin-main'),statuses=['New','Contacted','Walkthrough scheduled','Proposal sent','Won','Lost'];const input=(label,key,value,type='text')=>'<label>'+esc(label)+'<input data-key="'+key+'" type="'+type+'" value="'+esc(value)+'"></label>';const area=(label,key,value)=>'<label>'+esc(label)+'<textarea data-key="'+key+'">'+esc(value)+'</textarea></label>';const actions=()=>'<div class="admin-actions"><button class="button" id="save">Save changes</button><span class="saved-notice" role="status"></span></div>';const tools=i=>'<div class="record-tools"><label><input data-field="show" type="checkbox"> Show</label><button data-move="'+i+'" data-dir="-1">Move up</button><button data-move="'+i+'" data-dir="1">Move down</button><button data-remove="'+i+'">Remove</button></div>';
function readQuotes(){try{quotes=JSON.parse(localStorage.getItem(KEY+'-quotes')||'[]')}catch{quotes=[]}}
function render(){document.querySelectorAll('[data-screen]').forEach(b=>{if(b.dataset.screen===screen)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});let content='';if(screen==='quotes'){readQuotes();content='<h2>Quote requests</h2><label>Status filter<select id="status-filter"><option value="">All</option>'+statuses.map(x=>'<option>'+x+'</option>').join('')+'</select></label><div id="inbox">'+(quotes.length?quotes.map((q,i)=>'<article class="admin-record" data-quote="'+i+'"><h3>'+esc(q.company)+'</h3><p>'+esc(q.name)+'<br>'+esc(q.email)+'<br>'+esc(q.phone)+'</p><p>'+esc(q.interests.join(', '))+'<br>'+esc(q.employees)+' employees</p><p>'+esc(q.message)+'</p><p>'+esc(new Date(q.created).toLocaleString())+'</p><label>Status<select data-status>'+statuses.map(x=>'<option'+(x===q.status?' selected':'')+'>'+x+'</option>').join('')+'</select></label><label>Notes<textarea data-notes>'+esc(q.notes)+'</textarea></label><button data-delete-quote="'+i+'">Delete request</button></article>').join(''):'<p>Your quote requests will appear here when submitted in this browser.</p>')+'</div>'+actions()+'<button id="export" class="back-button">Export CSV</button>'}
else if(['services','industries','testimonials','news','faqs','photos'].includes(screen)){const titles={services:'Services',industries:'Industries',testimonials:'Testimonials',news:'News',faqs:'FAQ',photos:'Photos'};content='<h2>'+titles[screen]+'</h2>'+data[screen].map((x,i)=>'<article class="admin-record" data-index="'+i+'"><h3>'+esc(x.title||x.name||x.caption||'Photo')+'</h3>'+Object.entries(x).filter(([k])=>!['show','slug','option','groups'].includes(k)).map(([k,v])=>['text','items'].includes(k)?area(k==='items'?'Services, one per line':'Text',k,Array.isArray(v)?v.join('\n'):v):input(k,k,v)).join('')+(x.groups||[]).map((g,j)=>'<div data-group="'+j+'">'+input('Group title','group-title',g.title)+area('Services, one per line','group-items',g.items.join('\n'))+'</div>').join('')+(screen==='services'?'':tools(i))+'</article>').join('')+ (screen==='services'?'':'<button class="back-button" id="add">Add '+(screen==='photos'?'photo':'item')+'</button>')+actions()}
else if(screen==='info'){content='<h2>Business info</h2>'+Object.entries(data.info).map(([k,v])=>['numbers','counties','hours'].includes(k)?area(k==='numbers'?'Numbers, one per line':k,k,Array.isArray(v)?v.join('\n'):v):input(k==='notificationEmail'?'New request notification email (live site setting)':k,k,v,k.toLowerCase().includes('email')?'email':'text')).join('')+'<p>Quote requests are saved in this browser. Notification delivery begins when the site is connected for live service.</p>'+actions()}
else if(screen==='about'){content='<h2>About</h2>'+data.about.map((v,i)=>area('Paragraph '+(i+1),String(i),v)).join('')+actions()}
else if(screen==='announcement'){content='<h2>Announcement</h2><label><input data-key="enabled" type="checkbox"'+(data.announcement.enabled?' checked':'')+'> Show announcement</label>'+input('Text','text',data.announcement.text)+input('Link','url',data.announcement.url)+input('Start date','start',data.announcement.start,'date')+input('End date','end',data.announcement.end,'date')+actions()}
main.innerHTML=content;
if(data[screen]&&Array.isArray(data[screen]))main.querySelectorAll('[data-index]').forEach(el=>{const x=data[screen][el.dataset.index],show=el.querySelector('[data-field="show"]');if(show)show.checked=x.show!==false});
main.querySelector('#save')?.addEventListener('click',()=>{capture();const ok=screen==='quotes'?saveQuotes():ReliableStore.save(data);main.querySelector('.saved-notice').textContent=ok?'Saved on this device.':'Could not save. Check browser storage.'});
main.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('click',()=>{capture();const i=+b.dataset.move,j=i+(+b.dataset.dir);if(j>=0&&j<data[screen].length)[data[screen][i],data[screen][j]]=[data[screen][j],data[screen][i]];render()}));main.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{capture();data[screen].splice(+b.dataset.remove,1);render()}));main.querySelector('#add')?.addEventListener('click',()=>{capture();const x=screen==='testimonials'?{name:'',text:'',show:true}:screen==='news'?{title:'',url:'',show:true}:screen==='photos'?{url:'',caption:'',show:true}:{title:'',text:'',show:true};data[screen].push(x);render();main.querySelector('.admin-record:last-of-type input')?.focus()});
main.querySelector('#status-filter')?.addEventListener('change',e=>{main.querySelectorAll('[data-quote]').forEach(el=>el.hidden=e.target.value&&quotes[el.dataset.quote].status!==e.target.value)});main.querySelectorAll('[data-delete-quote]').forEach(b=>b.addEventListener('click',()=>{capture();quotes.splice(+b.dataset.deleteQuote,1);saveQuotes();render()}));main.querySelector('#export')?.addEventListener('click',()=>{capture();const cols=['created','status','company','name','email','phone','interests','employees','message','notes'];const csv=[cols,...quotes.map(q=>cols.map(k=>Array.isArray(q[k])?q[k].join('; '):q[k]||''))].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='quote-requests.csv';a.click();URL.revokeObjectURL(a.href)})}
function capture(){if(screen==='quotes'){main.querySelectorAll('[data-quote]').forEach(el=>{const q=quotes[el.dataset.quote];q.status=el.querySelector('[data-status]').value;q.notes=el.querySelector('[data-notes]').value});return}if(Array.isArray(data[screen])&&screen!=='about'){main.querySelectorAll('[data-index]').forEach(el=>{const x=data[screen][el.dataset.index];el.querySelectorAll(':scope > label [data-key]').forEach(field=>x[field.dataset.key]=field.dataset.key==='items'?field.value.split('\n').filter(Boolean):field.value);el.querySelectorAll('[data-group]').forEach(g=>{x.groups[g.dataset.group]={title:g.querySelector('[data-key="group-title"]').value,items:g.querySelector('[data-key="group-items"]').value.split('\n').filter(Boolean)}});const show=el.querySelector('[data-field="show"]');if(show)x.show=show.checked});return}main.querySelectorAll('[data-key]').forEach(el=>{const k=el.dataset.key;data[screen][k]=el.type==='checkbox'?el.checked:k==='numbers'?el.value.split('\n').filter(Boolean):el.value})}
function saveQuotes(){try{localStorage.setItem(KEY+'-quotes',JSON.stringify(quotes));return true}catch{return false}}
document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>{screen=b.dataset.screen;render()}));render();})();
