(()=>{'use strict';
const KEY='reliable-cleaning-v2',BASE=window.RELIABLE_DATA,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}let data={...structuredClone(BASE),...saved};
window.ReliableStore={KEY,BASE,data,save(d){try{localStorage.setItem(KEY,JSON.stringify(d));return true}catch{return false}},esc};
const url=u=>{try{const a=new URL(u,location.origin);return ['http:','https:'].includes(a.protocol)?a.href:'#'}catch{return '#'}};
const list=a=>'<ul class="service-list">'+a.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>';
function applyData(){document.querySelectorAll('[data-info]').forEach(el=>{const k=el.dataset.info,v=data.info[k];if(k==='phone'){el.textContent=v;el.href='tel:'+v.replace(/[^+\d]/g,'')}else el.href=url(v)});document.querySelectorAll('[data-info-text]').forEach(el=>el.textContent=data.info[el.dataset.infoText]);document.querySelectorAll('[data-number]').forEach(el=>el.textContent=data.info.numbers[el.dataset.number]);
if(saved.services)document.querySelectorAll('[data-service]').forEach(el=>{const s=data.services[el.dataset.service];el.innerHTML='<h2>'+esc(s.title)+'</h2><p>'+esc(s.text)+'</p>'+list(s.items)+(s.groups||[]).map(g=>'<h3>'+esc(g.title)+'</h3>'+list(g.items)).join('')});
if(saved.services)document.querySelectorAll('[data-service-card]').forEach(el=>{const x=data.services[el.dataset.serviceCard];(el.querySelector('h2 a,h3 a')||el.querySelector('h2,h3')).textContent=x.title;const p=el.querySelector('p');if(p)p.textContent=x.text});
['industries','testimonials','news','faqs'].forEach(k=>{if(!saved[k])return;const nodes=[...document.querySelectorAll('[data-record="'+k+'"]')];nodes.forEach(el=>{const x=data[k][el.dataset.index];if(!x||x.show===false){el.remove();return}if(k==='industries')el.querySelector('div').innerHTML='<h2>'+esc(x.title)+'</h2><p>'+esc(x.text)+'</p>';if(k==='testimonials')el.innerHTML='<p>'+esc(x.text)+'</p><cite>'+esc(x.name)+'</cite>';if(k==='news'){el.href=url(x.url);el.innerHTML='<h2>'+esc(x.title)+'</h2><span aria-hidden="true">↗</span>'}if(k==='faqs')el.innerHTML='<summary>'+esc(x.title)+'</summary><p>'+esc(x.text)+'</p>'});
const container=document.querySelector('[data-collection="'+k+'"]')|| (k==='industries'?document.querySelector('.industries'):k==='testimonials'&&document.body.dataset.route==='/testimonials/'?document.querySelector('.reviews'):null);if(container){container.innerHTML=data[k].filter(x=>x.show!==false).map(x=>k==='news'?'<a href="'+esc(url(x.url))+'" target="_blank" rel="noopener"><h2>'+esc(x.title)+'</h2><span>↗</span></a>':k==='faqs'?'<details><summary>'+esc(x.title)+'</summary><p>'+esc(x.text)+'</p></details>':k==='testimonials'?'<blockquote><p>'+esc(x.text)+'</p><cite>'+esc(x.name)+'</cite></blockquote>':'<article class="industry"><svg viewBox="0 0 80 60" aria-hidden="true"><path d="M5 52V24L25 12v12L45 12v12L65 12v40ZM16 38h8m12 0h8m12 0h8"/></svg><div><h2>'+esc(x.title)+'</h2><p>'+esc(x.text)+'</p></div></article>').join('')}});
if(saved.about)document.querySelectorAll('[data-about]').forEach(el=>el.innerHTML='<p>'+esc(data.about[el.dataset.about])+'</p>');
if(saved.photos)document.querySelectorAll('.about-intro>img').forEach(el=>{const p=data.photos.find(x=>x.show!==false);if(p){el.src=url(p.url);el.alt=p.caption}else el.remove()});
if(saved.photos&&['/about/','/careers/'].includes(document.body.dataset.route)){const visible=data.photos.filter(x=>x.show!==false);if(visible.length>1){const gallery=document.createElement('div');gallery.className='owner-photos';visible.slice(1).forEach(x=>{const figure=document.createElement('figure'),im=document.createElement('img'),caption=document.createElement('figcaption');im.src=url(x.url);im.alt=x.caption;im.loading='lazy';caption.textContent=x.caption;figure.append(im,caption);gallery.append(figure)});document.querySelector('.about-intro').parentElement.append(gallery)}}
if(data.announcement.enabled&&data.announcement.text){const now=new Date().toISOString().slice(0,10);if((!data.announcement.start||now>=data.announcement.start)&&(!data.announcement.end||now<=data.announcement.end)){const b=document.createElement('div');b.className='announcement';b.textContent=data.announcement.text;if(data.announcement.url){const a=document.createElement('a');a.href=url(data.announcement.url);a.textContent=b.textContent;b.replaceChildren(a)}document.querySelector('main')?.prepend(b)}}}
applyData();
const menu=document.querySelector('.menu-button');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);document.querySelector('#navigation').classList.toggle('is-open',open)});
const interests=['Janitorial Services: 3 days a week','Janitorial Services: 5 days a week (or more)','Cleaning on multiple shifts','Floor Maintenance Services','Daytime Porter Services','Disinfecting Services'];
function formMarkup(prefix){return '<form class="quote-form" novalidate><h2 id="'+prefix+'-title">Request a Quote</h2><p class="form-progress">Step 1 of 4</p><div class="form-step"><fieldset><legend>Interested In</legend><div class="interest-options">'+interests.map((v,i)=>'<label><input type="checkbox" name="interest" value="'+esc(v)+'">'+esc(v)+'</label>').join('')+'</div></fieldset><label>Approximate Number of Employees<select name="employees" required><option value="">Choose</option>'+['25','50','75','100','150','200','250','300+'].map(v=>'<option>'+v+'</option>').join('')+'</select></label></div><div class="form-step" hidden><label>Company<input name="company" autocomplete="organization" required></label><label>Name<input name="name" autocomplete="name" required></label></div><div class="form-step" hidden><label>Email<input name="email" type="email" autocomplete="email"></label><label>Phone<input name="phone" type="tel" autocomplete="tel"></label></div><div class="form-step" hidden><label>Message <span>(optional)</span><textarea name="message" rows="4"></textarea></label></div><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" class="back-button" hidden>Back</button><button type="submit" class="button next-button">Next</button></div></form>'}
function wireForm(root){const f=root.querySelector('form');let step=0;const steps=[...f.querySelectorAll('.form-step')],back=f.querySelector('.back-button'),next=f.querySelector('.next-button'),error=f.querySelector('.form-error');function show(){steps.forEach((el,i)=>el.hidden=i!==step);back.hidden=step===0;next.textContent=step===3?'Send':'Next';f.querySelector('.form-progress').textContent='Step '+(step+1)+' of 4';error.textContent='';if(step>0)steps[step].querySelector('input,select,textarea')?.focus()}
back.addEventListener('click',()=>{step--;show()});f.addEventListener('submit',e=>{e.preventDefault();error.textContent='';let msg='';if(step===0&&!f.querySelector('[name=interest]:checked'))msg='Choose the services you are interested in.';if(step===2&&!f.elements.email.value.trim()&&!f.elements.phone.value.trim())msg='Enter your email or phone so we can contact you.';const invalid=[...steps[step].querySelectorAll('input,select,textarea')].find(el=>!el.checkValidity());if(invalid){invalid.reportValidity();return}if(msg){error.textContent=msg;return}if(step<3){step++;show();return}const request={id:crypto.randomUUID(),created:new Date().toISOString(),status:'New',company:f.elements.company.value.trim(),name:f.elements.name.value.trim(),email:f.elements.email.value.trim(),phone:f.elements.phone.value.trim(),interests:[...f.querySelectorAll('[name=interest]:checked')].map(x=>x.value),employees:f.elements.employees.value,message:f.elements.message.value.trim(),notes:''};let inbox=[];try{inbox=JSON.parse(localStorage.getItem(KEY+'-quotes')||'[]');inbox.unshift(request);localStorage.setItem(KEY+'-quotes',JSON.stringify(inbox))}catch{error.textContent='Your browser could not save the request. Please call '+data.info.phone+'.';return}root.innerHTML='<div class="form-complete" role="status"><h2>Thanks.</h2><p>Reliable Cleaning will contact you about your free, no obligation quote.</p></div>'});return f}
const modal=document.querySelector('.modal-quote'),dialog=document.querySelector('#quote-dialog');let opener=null;
if(dialog){dialog.setAttribute('aria-labelledby','modal-title');document.querySelectorAll('.quote').forEach(button=>button.addEventListener('click',()=>{opener=button;modal.innerHTML=formMarkup('modal');const form=wireForm(modal);const selected=button.dataset.interest||document.body.dataset.defaultInterest;form.querySelectorAll('[name=interest]').forEach(el=>el.checked=el.value===selected);dialog.showModal();document.body.style.overflow='hidden';form.querySelector('input').focus()}));const close=()=>dialog.close();dialog.querySelector('.close-dialog').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus()})}
const inline=document.querySelector('.inline-quote');if(inline){inline.innerHTML=formMarkup('inline');wireForm(inline)}
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function clock(p,short=false){const mins=Math.round(17*60+Math.max(0,Math.min(1,p))*13*60),hour=Math.floor(mins/60)%24,m=mins%60;return (hour%12||12)+(short?'':':'+String(m).padStart(2,'0'))+' '+(hour>=12?'PM':'AM')}
function progress(){const total=document.documentElement.scrollHeight-innerHeight,p=total>0?scrollY/total:0;const w=Math.max(0,Math.min(1,p))*100;const fill=document.querySelector('.progress-fill'),c=document.querySelector('.progress-clock'),trail=document.querySelector('.bubble-trail');if(fill)fill.style.width=w+'%';const x=Math.min(innerWidth-95,Math.max(0,p*innerWidth));if(c){c.style.left=x+'px';c.textContent=clock(p,innerWidth<700)}if(trail)trail.style.left=Math.max(0,x-42)+'px'}addEventListener('scroll',progress,{passive:true});addEventListener('resize',progress);progress();
const shift=document.querySelector('.night-shift');if(shift){if(!reduce&&window.gsap&&window.ScrollTrigger){document.documentElement.style.setProperty('--nav-height',document.querySelector('.site-header').offsetHeight+'px');document.body.classList.add('js-motion');gsap.registerPlugin(ScrollTrigger);const rooms=[...shift.querySelectorAll('.shift-room')],marker=shift.querySelector('.crew-marker'),time=shift.querySelector('.shift-clock'),line=shift.querySelector('.shift-service'),finish=shift.querySelector('.morning-finish');const captions=rooms.map(el=>el.querySelector('.room-label strong').textContent+': '+el.querySelector('.room-label span').textContent);line.textContent='';function render(p){time.textContent=clock(p);const night=Math.min(1,p/.12);rooms.forEach((r,i)=>{r.querySelector('.room-night').style.opacity=night;const clean=Math.max(0,Math.min(1,(p-.14-i*.105)/.075));r.querySelector('.room-clean').style.opacity=clean;r.querySelector('.room-wash').style.opacity=clean*Math.max(0,Math.min(.42,(.94-p)*7));r.querySelector('.room-label').style.opacity=clean});const movement=Math.min(5,Math.max(0,(p-.14)/.105)),index=Math.floor(movement),fraction=movement-index;const current=rooms[index],nextroom=rooms[Math.min(5,index+1)];const br=shift.querySelector('.building').getBoundingClientRect(),rr=current.getBoundingClientRect(),nr=nextroom.getBoundingClientRect();marker.style.left=((rr.left+rr.width*.75)*(1-fraction)+(nr.left+nr.width*.75)*fraction-br.left)+'px';marker.style.top=((rr.top+rr.height*.35)*(1-fraction)+(nr.top+nr.height*.35)*fraction-br.top)+'px';marker.style.opacity=p>.12&&p<.88?'1':'0';line.textContent=p<.12?'':p<.88?captions[index]:'';finish.style.opacity=Math.max(0,Math.min(1,(p-.88)/.1))}render(0);ScrollTrigger.create({trigger:shift,start:()=>'top top+='+document.querySelector('.site-header').offsetHeight,end:()=>'+='+innerHeight*3,pin:'.shift-stage',scrub:true,onUpdate:self=>render(self.progress),invalidateOnRefresh:true});addEventListener('resize',()=>ScrollTrigger.refresh())}else{document.body.classList.add('no-motion');shift.querySelector('.shift-clock').textContent='6:00 AM'}}
})();
if(window.gsap&&window.ScrollTrigger&&!matchMedia('(prefers-reduced-motion: reduce)').matches){gsap.registerPlugin(ScrollTrigger);document.querySelectorAll('.process-node').forEach(el=>ScrollTrigger.create({trigger:el,start:'top 70%',end:'bottom 20%',toggleClass:'is-active'}))}
if(window.gsap&&window.ScrollTrigger&&matchMedia('(min-width:901px)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
const wrap=document.querySelector('.process-wrap');if(wrap){const nodes=[...wrap.querySelectorAll('.process-node')],panel=document.createElement('div');panel.className='process-detail';panel.setAttribute('aria-live','off');wrap.querySelector('.process-line').after(panel);const contents=nodes.map(n=>({title:n.querySelector('h2').textContent,list:n.querySelector('ul').cloneNode(true)}));nodes.forEach(n=>n.open=false);let active=-1;function select(index){if(index===active)return;active=index;nodes.forEach((n,i)=>{n.classList.toggle('is-selected',i===index);n.querySelector('summary').setAttribute('aria-expanded',String(i===index))});const h=document.createElement('h3');h.textContent=contents[index].title;panel.replaceChildren(h,contents[index].list.cloneNode(true))}nodes.forEach((n,i)=>n.querySelector('summary').addEventListener('click',e=>{e.preventDefault();select(i)}));select(0);ScrollTrigger.create({trigger:wrap,start:()=>'top top+='+ (document.querySelector('.site-header').offsetHeight+30),end:()=>'+='+innerHeight*2.5,pin:true,scrub:true,onUpdate:s=>select(Math.min(6,Math.floor(s.progress*7))),invalidateOnRefresh:true})}}
