import { AdminState, Customer, Staff, Job, Invoice } from "./types";

const iso = (d: Date) => d.toISOString().slice(0, 10);

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return iso(d);
}

function yearsAgo(n: number): string {
  const d = new Date();
  d.setFullYear(d.getFullYear() - n);
  return iso(d);
}

export const customers: Customer[] = [
  {
    id: "c1",
    name: "Summit Health Group",
    contact: "Dana Whitfield",
    email: "dana@summithealth.example",
    phone: "(260) 555-0142",
    type: "Medical",
    address: "1820 Medical Park Dr, Fort Wayne, IN",
    status: "active",
    frequency: "Daily",
    monthlyValue: 6400,
    since: yearsAgo(11),
    rating: 5,
    notes: "Three clinics. HIPAA-area protocols. Night service only.",
  },
  {
    id: "c2",
    name: "Allen County Logistics",
    contact: "Marcus Lee",
    email: "mlee@aclogistics.example",
    phone: "(260) 555-0198",
    type: "Industrial",
    address: "5500 Distribution Way, New Haven, IN",
    status: "active",
    frequency: "Daily",
    monthlyValue: 5200,
    since: yearsAgo(6),
    rating: 5,
    notes: "Warehouse + offices. High-traffic breakrooms.",
  },
  {
    id: "c3",
    name: "Lakeside Auto Group",
    contact: "Priya Raman",
    email: "priya@lakesideauto.example",
    phone: "(260) 555-0173",
    type: "Commercial",
    address: "300 Showroom Blvd, Fort Wayne, IN",
    status: "active",
    frequency: "Weekly",
    monthlyValue: 2100,
    since: yearsAgo(3),
    rating: 4,
    notes: "Showroom floor refinishing quarterly.",
  },
  {
    id: "c4",
    name: "Three Rivers Law Partners",
    contact: "Evelyn Cho",
    email: "echo@trlaw.example",
    phone: "(260) 555-0120",
    type: "Commercial",
    address: "110 W Berry St, Fort Wayne, IN",
    status: "active",
    frequency: "Bi-weekly",
    monthlyValue: 1450,
    since: yearsAgo(2),
    rating: 5,
  },
  {
    id: "c5",
    name: "Cedar Ridge Apartments",
    contact: "Tomas Vega",
    email: "tvega@cedarridge.example",
    phone: "(260) 555-0166",
    type: "Residential",
    address: "8800 Cedar Ridge Ln, Huntertown, IN",
    status: "active",
    frequency: "Weekly",
    monthlyValue: 1800,
    since: yearsAgo(1),
    rating: 4,
    notes: "Common areas + leasing office.",
  },
  {
    id: "c6",
    name: "Fort Wayne Dental Studio",
    contact: "Dr. Aisha Patel",
    email: "front@fwdental.example",
    phone: "(260) 555-0111",
    type: "Medical",
    address: "402 Maplewood Ave, Fort Wayne, IN",
    status: "active",
    frequency: "Daily",
    monthlyValue: 2950,
    since: yearsAgo(4),
    rating: 5,
  },
  {
    id: "c7",
    name: "Northcrest Shopping Center",
    contact: "Greg Mason",
    email: "gmason@northcrest.example",
    phone: "(260) 555-0155",
    type: "Commercial",
    address: "6230 N Clinton St, Fort Wayne, IN",
    status: "paused",
    frequency: "Weekly",
    monthlyValue: 0,
    since: yearsAgo(5),
    rating: 3,
    notes: "Paused for the season — revisit in fall.",
  },
  {
    id: "c8",
    name: "Bluffton Community Bank",
    contact: "Renee Schultz",
    email: "rschultz@blufftonbank.example",
    phone: "(260) 555-0188",
    type: "Commercial",
    address: "215 S Main St, Bluffton, IN",
    status: "prospect",
    frequency: "Bi-weekly",
    monthlyValue: 1200,
    since: daysFromNow(-4),
    rating: 0,
    notes: "Walkthrough completed. Quote sent — awaiting decision.",
  },
  {
    id: "c9",
    name: "Auburn Manufacturing Co.",
    contact: "Bill Hartman",
    email: "bhartman@auburnmfg.example",
    phone: "(260) 555-0144",
    type: "Industrial",
    address: "1200 Industrial Pkwy, Auburn, IN",
    status: "active",
    frequency: "Daily",
    monthlyValue: 4800,
    since: yearsAgo(8),
    rating: 4,
  },
  {
    id: "c10",
    name: "Riverbend Title Co.",
    contact: "Hannah Boyd",
    email: "hboyd@riverbendtitle.example",
    phone: "(260) 555-0177",
    type: "Commercial",
    address: "920 Coliseum Blvd, Fort Wayne, IN",
    status: "prospect",
    frequency: "Monthly",
    monthlyValue: 650,
    since: daysFromNow(-1),
    rating: 0,
    notes: "Inbound lead from website. Needs follow-up call.",
  },
];

export const staff: Staff[] = [
  {
    id: "s1",
    name: "Carmen Ortiz",
    role: "Supervisor",
    status: "on-shift",
    phone: "(260) 555-0211",
    hireDate: yearsAgo(14),
    hourlyRate: 28,
    rating: 5,
    certifications: ["OSHA 30", "Bloodborne Pathogens", "Floor Care"],
    assignedCustomerIds: ["c1", "c6"],
  },
  {
    id: "s2",
    name: "DeShawn Banks",
    role: "Crew Lead",
    status: "en-route",
    phone: "(260) 555-0222",
    hireDate: yearsAgo(7),
    hourlyRate: 22,
    rating: 5,
    certifications: ["OSHA 10", "Carpet Extraction"],
    assignedCustomerIds: ["c2", "c9"],
  },
  {
    id: "s3",
    name: "Mai Nguyen",
    role: "Floor Tech",
    status: "on-shift",
    phone: "(260) 555-0233",
    hireDate: yearsAgo(5),
    hourlyRate: 24,
    rating: 5,
    certifications: ["Floor Care", "Hard Surface Restoration"],
    assignedCustomerIds: ["c3", "c10"],
  },
  {
    id: "s4",
    name: "Robert Klein",
    role: "Cleaner",
    status: "on-shift",
    phone: "(260) 555-0244",
    hireDate: yearsAgo(2),
    hourlyRate: 18,
    rating: 4,
    certifications: ["OSHA 10"],
    assignedCustomerIds: ["c4", "c5"],
  },
  {
    id: "s5",
    name: "Latoya Bell",
    role: "Crew Lead",
    status: "off",
    phone: "(260) 555-0255",
    hireDate: yearsAgo(9),
    hourlyRate: 23,
    rating: 5,
    certifications: ["OSHA 30", "Green Cleaning"],
    assignedCustomerIds: ["c6", "c7"],
  },
  {
    id: "s6",
    name: "Hassan Ali",
    role: "Cleaner",
    status: "pto",
    phone: "(260) 555-0266",
    hireDate: yearsAgo(1),
    hourlyRate: 17,
    rating: 4,
    certifications: ["Bloodborne Pathogens"],
    assignedCustomerIds: ["c5"],
  },
  {
    id: "s7",
    name: "Grace Adler",
    role: "Cleaner",
    status: "on-shift",
    phone: "(260) 555-0277",
    hireDate: yearsAgo(3),
    hourlyRate: 19,
    rating: 5,
    certifications: ["OSHA 10", "Green Cleaning"],
    assignedCustomerIds: ["c9"],
  },
  {
    id: "s8",
    name: "Victor Salas",
    role: "Floor Tech",
    status: "en-route",
    phone: "(260) 555-0288",
    hireDate: yearsAgo(6),
    hourlyRate: 25,
    rating: 4,
    certifications: ["Floor Care", "OSHA 10"],
    assignedCustomerIds: ["c2"],
  },
];

const jobSeed: Omit<Job, "date">[] = [
  { id: "j1", customerId: "c1", crewIds: ["s1", "s4"], start: "18:00", end: "21:00", service: "Nightly Janitorial", status: "scheduled", checklistTotal: 24, checklistDone: 0 },
  { id: "j2", customerId: "c2", crewIds: ["s2", "s8"], start: "19:00", end: "23:00", service: "Warehouse + Office", status: "in-progress", checklistTotal: 32, checklistDone: 19 },
  { id: "j3", customerId: "c6", crewIds: ["s1"], start: "17:30", end: "19:30", service: "Medical Disinfection", status: "scheduled", checklistTotal: 18, checklistDone: 0 },
  { id: "j4", customerId: "c3", crewIds: ["s3"], start: "08:00", end: "12:00", service: "Showroom Floor Refinish", status: "completed", checklistTotal: 12, checklistDone: 12 },
  { id: "j5", customerId: "c9", crewIds: ["s2", "s7"], start: "20:00", end: "23:30", service: "Plant Floor + Breakrooms", status: "scheduled", checklistTotal: 28, checklistDone: 0 },
  { id: "j6", customerId: "c4", crewIds: ["s4"], start: "18:30", end: "20:00", service: "Office Janitorial", status: "scheduled", checklistTotal: 14, checklistDone: 0 },
  { id: "j7", customerId: "c5", crewIds: ["s7"], start: "09:00", end: "11:00", service: "Common Area Clean", status: "completed", checklistTotal: 16, checklistDone: 16 },
  { id: "j8", customerId: "c10", crewIds: ["s3"], start: "13:00", end: "14:00", service: "Walkthrough & Quote", status: "scheduled", checklistTotal: 6, checklistDone: 0 },
];

export const invoices: Invoice[] = [
  { id: "i1", number: "RC-2041", customerId: "c1", amount: 6400, issued: daysFromNow(-20), due: daysFromNow(-5), status: "paid" },
  { id: "i2", number: "RC-2042", customerId: "c2", amount: 5200, issued: daysFromNow(-18), due: daysFromNow(-3), status: "paid" },
  { id: "i3", number: "RC-2043", customerId: "c9", amount: 4800, issued: daysFromNow(-15), due: daysFromNow(0), status: "sent" },
  { id: "i4", number: "RC-2044", customerId: "c3", amount: 2100, issued: daysFromNow(-30), due: daysFromNow(-14), status: "overdue" },
  { id: "i5", number: "RC-2045", customerId: "c6", amount: 2950, issued: daysFromNow(-10), due: daysFromNow(5), status: "sent" },
  { id: "i6", number: "RC-2046", customerId: "c4", amount: 1450, issued: daysFromNow(-8), due: daysFromNow(7), status: "sent" },
  { id: "i7", number: "RC-2047", customerId: "c5", amount: 1800, issued: daysFromNow(-25), due: daysFromNow(-10), status: "paid" },
  { id: "i8", number: "RC-2048", customerId: "c8", amount: 1200, issued: daysFromNow(-2), due: daysFromNow(28), status: "draft" },
];

export function buildSeed(): AdminState {
  const jobs: Job[] = jobSeed.map((j, i) => ({
    ...j,
    // Spread jobs across yesterday/today/tomorrow for a lively schedule
    date: daysFromNow(i < 2 ? 0 : i < 6 ? 0 : 1),
  }));
  return {
    customers: JSON.parse(JSON.stringify(customers)),
    staff: JSON.parse(JSON.stringify(staff)),
    jobs,
    invoices: JSON.parse(JSON.stringify(invoices)),
  };
}
